project:
  type: book

book:
  title: "Introduction to R"  
  author: "Donatello, Lytal, Roualdes, Guo"
  date: "Fall 2025"
  search: true
  #downloads: [pdf, epub]
  
  chapters:
    - index.qmd
    - setup_tools.qmd
    - help.qmd
    - quarto.qmd
    - programming_in_r.qmd
    - dm.qmd  
    - factors.qmd
    - plots.qmd
    - dplyr.qmd
    - import.qmd
    - plots2.qmd
    - project.qmd
    - assignments.qmd
      

#bibliography: references.bib

format:
  html:
    theme: lumen
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

