project:
  type: book

book:
  title: "Introduction to R"  
  author: "Robin Donatello, Nicholas Lytal"
  date: "Spring 2026"
  search: true
  #downloads: [pdf, epub]
  
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Getting Started"
      chapters: 
        - setup_tools.qmd
        - quarto.qmd
        - programming_in_r.qmd
    - part: "Working with Data"
      chapters: 
        - dm.qmd  
        - factors.qmd
        - plots.qmd
        - dplyr.qmd
        - import.qmd
        - plots2.qmd
    - part: "Appendix"
      chapters: 
        - help.qmd
        - assignments.qmd
        - project.qmd
      

#bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight-style: arrow
    respect-user-color-scheme: true
    code-block-border-left: true
    code-line-numbers: false
    code-block-bg: true


execute: 
  freeze: auto

