project:
  type: book

book:
  title: "Introduction to R"  
  author: "Robin Donatello, Nicholas Lytal"
  # date: "January, 10, 2026"
  search: true
  #downloads: [pdf, epub]
  
  chapters:
    - index.qmd
    - overview.qmd
    - part: "Getting Started"
      chapters: 
        - setup_tools.qmd
        - quarto.qmd
        - intro_r.qmd
    - part: "Basic Functionality"
      chapters: 
        - dm.qmd  
        - factors.qmd
        - plots.qmd
        - dplyr.qmd
        - import.qmd
    - part: "Advanced Features"
      chapters: 
        - plots2.qmd
    - part: "Appendix"
      chapters: 
        - assignments.qmd
        - help.qmd
        - project.qmd
      
format:
  html:
    from: markdown+emoji
    theme: 
      light: flatly
      dark: darkly
    highlight-style: arrow
    respect-user-color-scheme: true
    code-block-border-left: true
    code-line-numbers: false
    code-block-bg: true

# code highlighting quarto extension https://github.com/shafayetShafee/line-highlight
filters:
  - line-highlight

execute: 
  freeze: auto
  message: false
  warning: false

